### ISSUE TITLE
specifying turbine heights as a vector

### ISSUE THREAD

**Issue by MrEtmAr** [YsoSirius/windfarmGA#18]
Hi
I am using this package for analyzing the reception zone for a wildlife monitoring system (ATLAS).
The system is based on several antennas that have to receive signals from tagged animals. Each of these antennas has a different height above ground level
Is it possible to choose the turbine heights (h1 in viewshed function ) as a vector of the same length of turbine_locs?

Thanks again for this great project

**Comment by trafficonese** [comment]
Hey, I am glad you find the package helpful.
This sounds like a great addition and should definitly be doable. 
I didn't need it for the wind turbines, as they all share the same height offset but for other applications it definitly makes sense.

**Comment by trafficonese** [comment]
Hey @MrEtmAr, I just published PR #19 which should fix the visibility issues and also allows `h1` to be a numeric vector.
Could you maybe test it out?

Unfortunately building and testing the package shows a lot of warnings and errors right now, due to the recent upgrade of CRS-handling. I am thinking of switching completely to `sf`, but that would probably break backwards compatibility.. So it will take a while until I can push the changes to CRAN.
